### ISSUE TITLE
[Feat] 챌린지 관련 API -1

### ISSUE THREAD

**Issue by pingowl** [potenday-project/IgoMoney_BE#16]
## Description
- 

## 📍 To-do
- [x] 챌린지 등록하기 (인당 1개 제한) API - startDate 지정
- [x] 챌린지 참여 신청 API
- [x] 챌린지 포기하기 API (뱃지 차감)
- [x] 참여중인 챌린지 기본정보 조회 API (상대방ID, title, 금액, 시작날짜)
