### ISSUE TITLE
[Feat] 챌린지 관련 API - 2

### ISSUE THREAD

**Issue by pingowl** [potenday-project/IgoMoney_BE#17]
## Description
- 

## 📍 To-do
- [x] 챌린지 인증(Record  엔티티) 관련 폴더링
- [x] Record 등록 API
- [x] Record 1건 조회 API
- [x] 사용자의 그날의 모든 Record 조회 API
- [x] 챌린지의 각 사용자 누적금액 조회 API
- [ ] 이미지 저장 세팅
