### ISSUE TITLE
[Feat] 카카오 회원탈퇴 - Feign Client 적용

### ISSUE THREAD

**Issue by pingowl** [potenday-project/IgoMoney_BE#54]
## Description
- 카카오 회원탈퇴 API에  Feign Client 적용
- 문제원인 : @PostMapping 에 consumes="application/x-www-form-urlencoded" 로 설정해야 Dto가 형식에 맞게 넘어갔다. consumes 설정 없이 @RequestHeader 로 헤더 설정하니까 JSON으로 넘어가서 에러가 났다. 근데 에러가 invalid_token으로 나와서 헷갈리게 만들었다. 

## 📍 To-do
- [x] AuthService - kakaoSignOut 코드 수정
- [x] KakaoSignOutRequest - 디폴트값 설정 수정
- [x] FeignClient - full logger 설정
