### ISSUE TITLE
[Feat] 홈화면 - 시작안한 챌린지 목록 조회, 챌린지 진행여부 조회

### ISSUE THREAD

**Issue by pingowl** [potenday-project/IgoMoney_BE#7]
## Description
- 홈화면에서 사용하는 API를 구현한다 : 시작안한 챌린지 목록 조회 API, 챌린지 진행여부 조회 API

## 📍 To-do
- [x] 챌린지 관련 폴더링
- [x] 챌린지 진행여부 조회 API  --> 회원 조회 API로 대신함
- [x] 시작안한 챌린지 목록 조회 API
- [x] 이모지 지원 자료형 적용 (utf8mb4)
